cat noise*/* | grep thread
cat noise*/* | grep max_iterations
cat noise*/* | grep population
cat noise*/* | grep num_elites
cat noise*/* | grep sim_time
cat noise*/* | grep tau
cat noise*/* | grep eta
cat noise*/* | grep epochs
cat noise*/* | grep crossover_rate
cat noise*/* | grep max_num_cells
cat noise*/* | grep num_rGCs
cat noise*/* | grep noise_level
cat noise*/* | grep train_size
cat noise*/* | grep test_size
cat noise*/* | grep label_thre
cat noise*/* | grep internal_connection
cat noise*/* | grep w_auc
cat noise*/* | grep w_synapses
