#! /usr/bin/env python3

import numpy as np
from scipy.stats import norm
import sys

with open('PARAM', 'r') as f:
    for i, line in enumerate(f):
        if i == 3:
            TRAIN_SIZE = int(line.split(' = ')[1])
        if i == 4:
            TEST_SIZE = int(line.split(' = ')[1])
        if i == 10:
            MAX_CELLS = int(line.split(' = ')[1]) 

C = (MAX_CELLS - 1) // 2

data = np.ones((TRAIN_SIZE + TEST_SIZE, MAX_CELLS)) * 0.05
r = np.random.uniform(low=5, high=C*0.8, size=data.shape[0]).astype(np.int32)
width = r * 2

gaussian = norm.pdf(np.arange(-5, 6), scale=3)

for i in range(data.shape[0]):
    # Create rectangle signal
    data[i, C - r[i]: C + r[i] + 1] = 1

    data[i] = np.abs(np.random.normal(data[i], 0.2, size=MAX_CELLS))

    data[i] = np.convolve(data[i], gaussian, 'same')

mins = data.min(axis=1)
maxs = data.max(axis=1)
data = (data - mins[:, None]) / (maxs - mins)[:, None]

if sys.argv[1] == '--plot':
    import matplotlib.pyplot as plt
    for i in range(data.shape[0]): 
        plt.plot(data[i])
    plt.show()

np.savetxt('DATA', data, fmt='%0.5f')
np.savetxt('SW', width, fmt='%d')
